image: node:10

test:
  script:
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - apt update && apt install git -y
    - git clone -b $CI_COMMIT_REF_NAME https://gitlab+deploy-token-147653:i6FB3YR1UUsD4EtCkL1H@gitlab.com/pencillabs/ej/conversation-component.git
    - cd conversation-component/conversations
    - npm install @stencil/core@latest --save-exact && node_modules/@stencil/core/bin/stencil test --spec
  artifacts:
    paths:
      - conversations/
  tags:
    - osf

publish-npm:
  variables:
    NPM_TOKEN: "d4da3499-2c61-4f58-92d8-eea6394e3cec"
  script:
    - cd conversations
    - npm install -g @stencil/core@latest --save-exact && npm install
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - make publish
  tags:
    - osf
  only:
    refs:
      - master
    changes:
      # deploy to npm only when package.json changes
      - "conversations/package.json"

