test:
  image: node:10
  script:
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - apt update && apt install git -y
    - git clone -b $CI_COMMIT_REF_NAME https://gitlab+deploy-token-147653:i6FB3YR1UUsD4EtCkL1H@gitlab.com/pencillabs/ej/conversation-component.git
    - cd conversation-component/conversations
    - npm install @stencil/core@latest --save-exact && node_modules/@stencil/core/bin/stencil test --spec
  tags:
    - osf
