image: node:12
stages:
  - test
  # TODO: fix this https://gitlab.com/pencillabs/ej/conversation-component/-/issues/1
  # - publish

run_tests:
  stage: test
  script:
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - apt update && apt install git -y
    - git clone -b $CI_COMMIT_REF_NAME https://gitlab+deploy-token-147653:i6FB3YR1UUsD4EtCkL1H@gitlab.com/pencillabs/ej/conversation-component.git
    - cd conversation-component/conversations
    - npm install @stencil/core@latest --save-exact && node_modules/@stencil/core/bin/stencil test --spec
  artifacts:
    paths:
      - conversations/
  tags:
    - osf
  # publish_to_npm:
  #   stage: publish
  #   variables:
  #     NPM_TOKEN: "e5585806-c701-4516-8d28-3734184abefa"
  #   script:
  #     - cd conversations
  #     - npm install -g @stencil/core@latest --save-exact && npm install
  #     - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  #     - make publish
  #   tags:
  #     - osf
  #   only:
  #     refs:
  #       - master
  #     changes:
  #       # deploy to npm only when package.json changes
  #       - "conversations/package.json"
