/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  API,
} from './components/my-component/api';

export namespace Components {
  interface EjConversation {
    'api': API;
    'comment': any;
    'conversation': any;
    'newCommentContent': string;
  }
}

declare global {


  interface HTMLEjConversationElement extends Components.EjConversation, HTMLStencilElement {}
  var HTMLEjConversationElement: {
    prototype: HTMLEjConversationElement;
    new (): HTMLEjConversationElement;
  };
  interface HTMLElementTagNameMap {
    'ej-conversation': HTMLEjConversationElement;
  }
}

declare namespace LocalJSX {
  interface EjConversation {
    'api'?: API;
    'comment'?: any;
    'conversation'?: any;
    'newCommentContent'?: string;
  }

  interface IntrinsicElements {
    'ej-conversation': EjConversation;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ej-conversation': LocalJSX.EjConversation & JSXBase.HTMLAttributes<HTMLEjConversationElement>;
    }
  }
}


