/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EjOpinionButton {}
}

declare global {


  interface HTMLEjOpinionButtonElement extends Components.EjOpinionButton, HTMLStencilElement {}
  var HTMLEjOpinionButtonElement: {
    prototype: HTMLEjOpinionButtonElement;
    new (): HTMLEjOpinionButtonElement;
  };
  interface HTMLElementTagNameMap {
    'ej-opinion-button': HTMLEjOpinionButtonElement;
  }
}

declare namespace LocalJSX {
  interface EjOpinionButton {}

  interface IntrinsicElements {
    'ej-opinion-button': EjOpinionButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ej-opinion-button': LocalJSX.EjOpinionButton & JSXBase.HTMLAttributes<HTMLEjOpinionButtonElement>;
    }
  }
}


